---
title: "INLA Simulation study"
author: "Xiang Ye"
date: "2023-03-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(MASS)
library(sp)
library(gstat)
library(sf)
library(plyr)
library(dplyr)
library(ggplot2)
library(gridExtra)
library(tidyverse)
library(viridis)
library(INLA)
library(maptools)
library(automap)
```

# Data

```{r}
load('PollutantsMExicoCity2021.RData')
```

```{r}
CDMX_border<-st_union(CDMX_sf)

ggplot() + 
  geom_sf(data = CDMX_sf, color = "white") + 
  geom_sf(data = CDMX_Nsf, color = "gray",bg="gray")+
  geom_sf(data=CDMX_border,color='black',bg="transparent")+
  coord_sf()+geom_point(data=Stations,aes(x=lon,y=lat),col='blue',size=2)

###Creating the mesh
coords.sp.aux<-SpatialPoints(Stations[,5:6],proj4string = CRS("+proj=longlat +datum=WGS84"))
bbox(coords.sp.aux)
##transformed to KM
coords.sp<-spTransform(coords.sp.aux,CRS("+proj=utm +units=km +datum=WGS84 +zone=14"))
bbox(coords.sp)
```

# Data Simulation

```{r}
# Define Matern covariance function
matern.cov<-function(d, nu = 2, kappa = 1,sig=1){
  if(nu == 0.5){
    return(sig^2*exp( - d * alpha))
  }
  gamma.d<- ifelse(d>0,sig^2 * (2^(1-nu)/ gamma(nu)) * ((d*kappa)^nu) * besselK(d*kappa, nu),sig^2)
  return(gamma.d)
}
```

```{r}
# Function to simulate the data
GP.data <- function(coordinates,nu=1,kappa=1,sig=1,mu=50){
  coordinates = as.data.frame(coordinates)
  n <- nrow(coordinates)
  D <- dist(coordinates)
  
  ## Simulation
  sim_mat <- matern.cov(as.matrix(D),nu=nu,kappa=kappa,sig=sig)
  data <- mvrnorm(mu=rep(mu,n), Sigma=sim_mat)
  return(data)
}
```


```{r}
set.seed(123)
Gaussian_dat = abs(GP.data(as.data.frame(coords.sp), nu=1, kappa=4, sig=15, mu=45))
Gaussian_dat
```

# INLA

```{r}
# Function include constructing a mesh, fit an SPDE, and do the INLA to find the posteriors of the parameters
mesh.test2 <- function(data, coordinates, boundary, max_edge_1,
                       max_edge_2, min_angle_1, min_angle_2,
                       cutoff, offset_1, offset_2){
  
  ## data: the data
  ## coordinates: the longitude and latitude of the data point (recommended in kilometers)
  ## boundary: boundary of the mesh
  
  ## max_edge_1: maximum allowed triangle edge length in the inner domain
  ## max_edge_2: maximum allowed triangle edge length in the outer extension
  
  ## min_angle_1: the minimum internal angles of the triangles in the inner domain
  ## min_angle_2: the minimum internal angles of the triangles in the outer extension
  ### min_angle values up to 21 guarantee the convergence of the algorithm
  
  ## cutoff: to set the minimum allowed distance between points
  
  ## offset_1: set the automatic extension distance in direction 1
  ## offset_2: set the automatic extension distance in direction 2 
  
  df <- as.data.frame(coordinates)
  df$dat = data
  colnames(df) <- c('lon','lat','dat')
  
  mesh0 <- inla.mesh.2d(loc = coordinates, boundary = boundary,
                        max.edge = c(max_edge_1,max_edge_2),
                        min.angle = c(min_angle_1,min_angle_2),
                        cutoff=cutoff,
                        offset=c(offset_1,offset_2))
  
  ## priors for SPDE
  ## sigma
  sigma_0 <- sd(df$dat)+0.1
  
  ## range
  vgm.emp <- variogram(dat~1, data = df,
                       locations = ~lon+lat)
  fitvariogram<-fit.variogram(vgm.emp, vgm(c( "Mat")), 
                              fit.kappa = TRUE)
  range_0 <- fitvariogram$range[2]
  
  spde0 <- inla.spde2.pcmatern(
    mesh = mesh0, alpha = 2,
    prior.range = c(range_0,0.85),
    prior.sigma = c(sigma_0,0.01))
  
  A <- inla.spde.make.A(mesh0, loc = coordinates)
  
  dat.stk <- inla.stack(
    data = list(resp = df$dat),
    A = list(A, 1),
    effects = list(i = 1:spde0$n.spde,
                   beta0 = rep(1, nrow(df))))
  
  
  res <- inla(resp ~ 0 + beta0 + f(i, model = spde0),
              data = inla.stack.data(dat.stk),
              control.predictor = list(A = inla.stack.A(dat.stk)),
              control.compute = list(dic = TRUE))
  
  ## expectation of the posterior standard error
  post.se <- inla.tmarginal(function(x) sqrt(1 / exp(x)),
                            res$internal.marginals.hyperpar[[1]])
  post.se.e <- inla.emarginal(function(x) x, post.se)
  
  precision = inla.emarginal(function(x) x, res$marginals.hyperpar[[1]])
  range.hat = inla.emarginal(function(x) x, res$marginals.hyperpar[[2]])
  sigma.hat = inla.emarginal(function(x) x, res$marginals.hyperpar[[3]])
  dic = res$dic$dic
  
  hyperparameters = list(range0 = range_0, sigma0 = sigma_0, range_hat = range.hat, sigma_hat = sigma.hat, dic = dic, post_expect_se = post.se.e, precision = precision)
  
  return(hyperparameters)
}
```

```{r}
# The border information
border.aux<- unionSpatialPolygons(CDMXpol,IDs = rep(1,16))
bbox(border.aux)
border<-spTransform(border.aux,CRS("+proj=utm +units=km +datum=WGS84 +zone=14"))
bbox(border)
```

```{r,warning=FALSE}
# Run the INLA process to find the posteriors
mesh.test2(data = Gaussian_dat, coordinates=coords.sp,
           boundary=border, max_edge_1=10, max_edge_2=12,
           min_angle_1=20, min_angle_2=20, cutoff=5,
           offset_1=5, offset_2=7)
```

```{r,warning=FALSE}
# For different random seeds, the results are different
set.seed(564)
mesh.test2(data = abs(GP.data(coords.sp,nu=1,kappa=4,sig=30,mu=50)), 
           coordinates=coords.sp,
           boundary=border, max_edge_1=10, max_edge_2=12,
           min_angle_1=20, min_angle_2=20, cutoff=5,
           offset_1=5, offset_2=7)

```

# The testing range of the parameters

```{r}
# All parameters try all number in one decimal places.
# If possible, 2 decimal places would be better (but perhaps too intensive)
## max_edge_1: 5~20
## max_edge_2: 5~20
## min_angle_1: 10~30
## min_angle_2: 10~30
## cutoff: 1~20
## offset_1: 1~20
## offset_2: 1~20
```


# find better mesh (example)

```{r,warning=FALSE}
# Run the INLA process to find the posteriors
mesh.test2(data = Gaussian_dat, coordinates=coords.sp,
           boundary=border, max_edge_1=10, max_edge_2=12,
           min_angle_1=20, min_angle_2=20, cutoff=5,
           offset_1=5, offset_2=7)
```


```{r}
edge1 = c(1:20)
```

```{r,warning=FALSE}
posteriors = as.data.frame(matrix(0,20,8))
colnames(posteriors)=c("max_edge","prior range", "prior sigma", "posterior range", "posterior sigma", "dic", "post_expect_se", "precision")
```

```{r}
posteriors.edge1 = posteriors
```

```{r}
set.seed(89275)
dat2 = abs(GP.data(coords.sp,nu=1,kappa=4,sig=15,mu=45))
```

```{r,warning=FALSE}
for (i in edge1){
  post = mesh.test2(data = dat2, coordinates=coords.sp,
             boundary=border, max_edge_1=i, max_edge_2=12,
             min_angle_1=20, min_angle_2=20, cutoff=5,
             offset_1=5, offset_2=7)
  posteriors.edge1[i,1]=i
  posteriors.edge1[i,2]=post$range0
  posteriors.edge1[i,3]=post$sigma0
  posteriors.edge1[i,4]=post$range_hat
  posteriors.edge1[i,5]=post$sigma_hat
  posteriors.edge1[i,6]=post$dic
  posteriors.edge1[i,7]=post$post_expect_se
  posteriors.edge1[i,8]=post$precision
}
```

```{r,warning=FALSE}
posteriors.edge1
```




## cutoff

```{r}
cutoffs = seq(3,9,0.1)
```



```{r}
posteriors.cutoff = as.data.frame(matrix(0,61,7))
colnames(posteriors.cutoff)=c("max_edge","prior range", "prior sigma", "posterior range", "posterior sigma","post_expect_se", "precision")
```

```{r,warning=FALSE}
n = 1
for (i in cutoffs){
  post = mesh.test2(data = Gaussian_dat, coordinates=coords.sp,
             boundary=border, max_edge_1=10, max_edge_2=12,
             min_angle_1=20, min_angle_2=20, cutoff=i,
             offset_1=5, offset_2=7)
  posteriors.cutoff[n,1]=i
  posteriors.cutoff[n,2]=post$range0
  posteriors.cutoff[n,3]=post$sigma0
  posteriors.cutoff[n,4]=post$range_hat
  posteriors.cutoff[n,5]=post$sigma_hat
  posteriors.cutoff[n,6]=post$post_expect_se
  posteriors.cutoff[n,7]=post$precision
  n = n + 1
}
```

```{r,warning=FALSE}
posteriors.cutoff
```

```{r,warning=FALSE}
# Run the INLA process to find the posteriors
mesh.test2(data = Gaussian_dat, coordinates=coords.sp,
           boundary=border, max_edge_1=10, max_edge_2=12,
           min_angle_1=20, min_angle_2=20, cutoff=0.1,
           offset_1=5, offset_2=7)
```









```{r,warning=FALSE}
mesh.1 <- inla.mesh.2d(loc = coords.sp,boundary = border,
                          max.edge=c(10, 12),
                          cutoff=5) 
mesh.1$n
# mesh size
plot(spTransform(CDMXpol,CRS("+proj=utm +units=km +datum=WGS84 +zone=14")),
     xlim=c(450,510),ylim=c(2080,2190))
plot(mesh.1,add=TRUE)
plot(coords.sp,add=TRUE,pch=20,col=2)
```

```{r,warning=FALSE}
mesh.1 <- inla.mesh.2d(loc = coords.sp,boundary = border,
                          max.edge=c(15, 5),
                          cutoff=3,) 
mesh.1$n
# mesh size
plot(spTransform(CDMXpol,CRS("+proj=utm +units=km +datum=WGS84 +zone=14")),
     xlim=c(450,510),ylim=c(2080,2190))
plot(mesh.1,add=TRUE)
plot(coords.sp,add=TRUE,pch=20,col=2)
```


# Output

```{r}
load("Output.RData")
```

```{r}
OUT.Sim[[1]]
```



## Output Analysis

```{r}
nu = 1
kappa = 4
## true range
range_0 = sqrt(8*nu)/kappa
range_0
```

```{r}
## true sigma
sigma_0 = 15
```

```{r}
lost = as.data.frame(matrix(0,nrow=80, ncol=8))
colnames(lost)=c("comb","range","sd","DIC","range_sd","edge1","edge2","cutoff")
```

```{r}
options(scipen = 999)
for (i in c(1:80)){
  lost[i,1] = i
  lost[i,2] = 1/10 * sum((OUT.Sim[[i]]$`posterior range` - range_0)^2)
  lost[i,3] = 1/10 * sum((OUT.Sim[[i]]$`posterior sigma` - sigma_0)^2)
  lost[i,4] = 1/10 * sum(OUT.Sim[[i]]$dic)
  lost[i,5] = 0.5*1/10 * sum((OUT.Sim[[i]]$`posterior range` - range_0)^2) + 0.5*1/10 * sum((OUT.Sim[[i]]$`posterior sigma` - sigma_0)^2)
}
```

```{r}
lost
```

```{r}
dplyr::arrange(lost, range)
```

```{r}
dplyr::arrange(lost, sd)
```

```{r}
dplyr::arrange(lost, DIC)
```

```{r}
## 0.5*range + 0.5*sd
dplyr::arrange(lost, range_sd)
```

### Compare the meshes

```{r,warning=FALSE}
## similar to the dissertation one with only edge and cutoff parameters
mesh.1 <- inla.mesh.2d(loc = coords.sp,boundary = border,
                          max.edge=c(10, 12),
                          cutoff=5) 
mesh.1$n
# mesh size
plot(spTransform(CDMXpol,CRS("+proj=utm +units=km +datum=WGS84 +zone=14")),
     xlim=c(450,510),ylim=c(2080,2190))
plot(mesh.1,add=TRUE)
plot(coords.sp,add=TRUE,pch=20,col=2)
```

```{r,warning=FALSE}
# best range
mesh.range <- inla.mesh.2d(loc = coords.sp,boundary = border,
                          max.edge=c(15, 15),
                          cutoff=7) 
mesh.range$n
# mesh size
plot(spTransform(CDMXpol,CRS("+proj=utm +units=km +datum=WGS84 +zone=14")),
     xlim=c(450,510),ylim=c(2080,2190))
plot(mesh.range,add=TRUE)
plot(coords.sp,add=TRUE,pch=20,col=2)
```

```{r,warning=FALSE}
# best sd
mesh.sd <- inla.mesh.2d(loc = coords.sp,boundary = border,
                          max.edge=c(5, 15),
                          cutoff=1) 
mesh.sd$n
# mesh size
plot(spTransform(CDMXpol,CRS("+proj=utm +units=km +datum=WGS84 +zone=14")),
     xlim=c(450,510),ylim=c(2080,2190))
plot(mesh.sd,add=TRUE)
plot(coords.sp,add=TRUE,pch=20,col=2)
```

```{r,warning=FALSE}
# best DIC
mesh.dic <- inla.mesh.2d(loc = coords.sp,boundary = border,
                          max.edge=c(20, 5),
                          cutoff=5) 
mesh.dic$n
# mesh size
plot(spTransform(CDMXpol,CRS("+proj=utm +units=km +datum=WGS84 +zone=14")),
     xlim=c(450,510),ylim=c(2080,2190))
plot(mesh.dic,add=TRUE)
plot(coords.sp,add=TRUE,pch=20,col=2)
```

```{r,warning=FALSE}
mesh.comb <- inla.mesh.2d(loc = coords.sp,boundary = border,
                          max.edge=c(15, 5),
                          cutoff=3) 
mesh.comb$n
# mesh size
plot(spTransform(CDMXpol,CRS("+proj=utm +units=km +datum=WGS84 +zone=14")),
     xlim=c(450,510),ylim=c(2080,2190))
plot(mesh.comb,add=TRUE)
plot(coords.sp,add=TRUE,pch=20,col=2)
```










## Output plots

```{r}
edge1 = c(rep(5,20), rep(10,20), rep(15,20), rep(20,20))
edge2 = rep(c(rep(5,5), rep(10,5), rep(15,5), rep(20,5)),4)
cutoff = rep(c(1,3,5,7,9),16)
```

```{r}
lost$edge1 = edge1
lost$edge2 = edge2
lost$cutoff = cutoff
```

```{r}
lost
```

```{r}
ggplot(data = lost %>% dplyr::filter(cutoff==1), aes(x=edge1, y=edge2, z=range)) +
  geom_tile()+ggtitle("ranges when cutoff=1")+scale_fill_viridis()
```

```{r}
lost %>% dplyr::filter(cutoff==1)
```


























